#Pull base image
FROM ubuntu

RUN \
  apt-get update


#Install python
RUN apt-get install -y python2.7

#Install pip
RUN apt-get install -y python-pip

#Install luigi
RUN pip install luigi

#Install geojson
RUN pip install geojson

#Install shapely
RUN pip install shapely

#Install libgeos-dev
RUN apt-get install -y libgeos-dev

#Install sklearn
RUN apt-get install -y python-sklearn 

#Install mapnik
RUN pip install mapnik

#Install lxml
RUN pip install lxml

#Install Cython
RUN pip install Cython

#Install numpy
RUN pip install numpy

#Install matplotlib
RUN pip install matplotlib

#Install libatlas-base-dev
RUN apt-get install -y libatlas-base-dev

#Install tsne
RUN pip install tsne

#Insall psycopg2
RUN pip install psycopg2

#Install annoy
RUN pip install annoy

#Install werkzeug
RUN pip install werkzeug

#Install marisa-trie
RUN pip install marisa-trie

#Install TileStache
RUN pip install TileStache

#Install colour 
RUN pip install colour

#Install falcon
RUN pip install falcon

#Install libffi-dev
RUN apt-get install libffi-dev

#Install libssl-dev
RUN apt-get install -y libssl-dev

#Install cairocffi
RUN pip install cairocffi

#Install jinja2
RUN pip install jinja2


#Install qt
RUN apt-get install -y qt4-default

#Install cmake
RUN apt-get install -y cmake

#Install pygsp==0.4.0
RUN pip install pygsp==0.4.0

#Install cairo
RUN apt-get install -y libcairo2-dev

#Install pandas
RUN pip install pandas




#Define default command
CMD bash
